language: python
services:
  - docker
install:
  - cp local_settings.cfg.example local_settings.cfg
before_script:
  - pip install tox
script: tox
matrix:
  include:
    - python: "3.7"
      env: TOXENV=py37
    - python: "3.7"
      env: TOXENV=linting
notifications:
  email: false
